xun082/create-neat

- LICENSE
- README.md
修改markdown文件
- Closes #
- Related to #
> docs: 📚 修改markdown文件

- packages/core/src/utils/createApp.ts
- packages/core/src/utils/createCommitlint.ts
- packages/core/src/utils/createFile.ts
- packages/core/src/utils/fileController.ts
优化创建阶段 select，使得单次 Ctrl+C 即可直接退出中断。给 core 部分函数加入进程退出逻辑
select 阶段，一次 Ctrl + C 不会退出进程，而是进入下一个选择阶段
> feat: 优化创建阶段 select，使得单次 Ctrl+C 即可直接退出中断。给 core 部分函数加入进程退出逻辑

- package.json
```
[x] Bugfix
[ ] Feature
```
修改本地 lint-stage 流程
```
[x] Yes
[ ] No
```
> feat: 修改本地 lint-stage 流程

- packages/core/src/utils/createAppTest.ts
- packages/core/src/utils/dependenciesInstall.ts
- packages/core/src/utils/preset.ts
- packages/core/src/utils/select.ts
```
[ ] Bugfix
[x] Feature
```
- Closes #40 
```
[ ] Yes
[x] No
```
> feat: add devDependencies install: (#40)

- CONTRIBUTING.md
- contributing/CONTRIBUTING.en.md
- contributing/CONTRIBUTING.zh_CN.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: add CONTRIBUTING documents in both Chinese and Englist
```
- Closes #35 
- Related to #
```
[ ] Yes
[x] No
```
> feat: 版本更新1.1 (#35)

- package.json
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/utils/createAppTest.ts
- packages/core/src/utils/createFiles.ts
- packages/core/src/utils/dependenciesInstall.ts
- pnpm-lock.yaml
```
[✅] Bugfix
[ ] Feature
```
- Closes #57 
- Related #24 
修复spawn中不支持win32平台的bug
```
[ ] Yes
[✅] No
```
> fix:修复spawn中不支持win32平台的bug(#57)

- .gitignore
- .vscode/settings.json
- packages/core/src/utils/getnpmSource.ts
- packages/core/src/utils/preset.ts
- packages/core/src/utils/select.ts
- pnpm-lock.yaml
- registries.json
```
[ ] Bugfix
[✅ ] Feature
```
- Closes #52
- Related to #24
添加npm源的选择
```
[✅ ] Yes
[ ] No
```
> feat: 包管理器的安装和镜像源的选择

- myApp/package.json
- packages/core/src/utils/Generator.ts
- packages/core/src/utils/createAppTest.ts
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
- Closes #45 
```
[ ] Yes
[x] No
```
> refactor: merge生产环境与开发环境的plugin模块引入

- pnpm-lock.yaml
- scripts/check_commit_msg.sh
```
[ ] Bugfix
[ ] Feature
[ x] CI related changes
```
- Closes #77
- Related to #
从 commitlint.config.js 读取规则
```
[ ] Yes
[x ] No
```
> ci: 从 commitlint.config.js 读取规则

- packages/core/src/utils/dependenciesInstall.ts
```
[ ] Bugfix
[✅] Feature
```
- Closes #104
有些插件可能需要dependencies依赖 但是目前只支持devDependencies安装
```
[ ] Yes
[✅] No
```
> feat: 🚀 增加dependencies的安装方式

- packages/utils/src/core/createHash.ts
- packages/utils/src/core/getHttpsConfig.ts
- packages/utils/src/core/getIpAddress.ts
- packages/utils/src/core/getJsonFileInfo.ts
- packages/utils/src/core/getPackagePath.ts
- packages/utils/src/core/getResolveApp.ts
- packages/utils/src/core/useCssPreset.ts
```
[ ] Bugfix
[ ] Feature
```
- Closes #76
为packages\utils\src\core路径下的文件添加文档注释
```
[ ] Yes
[x] No
```
> feat: add jsdoc of utils

- scripts/check_commit_msg.sh
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
- Closes #111 
- Related to # 
```
[ ] Yes
[ ] No
```
> ci: commit信息校验兼容revert

- packages/core/src/utils/Generator.ts
- packages/core/src/utils/constants.ts
```
[x] Bugfix
[ ] Feature
```
- Closes #118
- Related to #
- 使用__dirname代替process.cwd()
- loadmodule函数中通过相对路径定位到plugin
```
[ ] Yes
[x] No
```
> fix: 测试环境loadmodule全路径适配

- .husky/pre-commit
- scripts/check-git-config.sh
```
[ ] Bugfix
[x] Feature
```
- Closes #107 
- Related to #107 
```
[ ] Yes
[x] No
```
> feat: 新增对行末换行符、git大小写敏感配置的检查

- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- scripts/check_commit_msg.sh
```
[ ] Bugfix
[ ] Feature
[ x] CI related changes
```
- Closes #
- Related to #
修改提交规范,允许提交 feat(xxx) 等带括号的描述
```
[ ] Yes
[ x] No
```
> ci: 🎡 修改提交规范,允许提交 feat(xxx) 等带括号的描述

- .github/workflows/deploy-vitepress.yml
```
[ ] Bugfix
[ ] Feature
[x ] CI related changes
```
- Closes #131 
- Related to #
添加 vitepress 自动部署
```
[ ] Yes
[x ] No
```
> ci: 🎡 添加 vitepress 自动部署

- docs/.vitepress/config/nav.js
- docs/contributors.md
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe:
```
- Closes #
- Related to #
添加贡献者名单
```
[ ] Yes
[ ] No
```
> docs: 添加贡献者名单

- packages/@plugin/plugin-babel/index.cjs
- packages/core/package.json
- packages/core/src/utils/Generator.ts
- packages/core/src/utils/ast.ts
- packages/core/src/utils/createAppTest.ts
- packages/core/template/vite.config.js
- packages/core/template/webpack.config.js
- pnpm-lock.yaml
```
[ ] Bugfix
[✅] Feature
```
- Closes #36 
- Related to #24  
使用unplugin适配不同构建工具
```
[✅] Yes
[ ] No
```
> feat: ✨ merge build tool config by ast

- .github/workflows/deploy-vitepress.yml
```
[ ] Bugfix
[ ] Feature
[ x] CI related changes
```
- Closes #
- Related to #
修复ci的报错问题
```
[ ] Yes
[ x] No
```
> ci: 🎡 修复ci的报错问题

- docs/index.md
```
[ ] Bugfix
[ ] Feature
[x ] Other... Please describe:
```
- Closes #
- Related to #
修改 vitepress 首页文档
```
[ ] Yes
[x ] No
```
> docs: 📚 修改 vitepress 首页文档

- packages/@plugin/plugin-eslint/generator/index.cjs
- packages/@plugin/plugin-eslint/package.json
- packages/core/src/utils/configMap.ts
- pnpm-lock.yaml
```
[ ] Bugfix
[x] Feature
```
- Closes #133 #134 
- Related to #31 
Initial implementation of eslint-plugin。
```
[ ] Yes
[x] No
```
> 实现 eslint 插件开发

- packages/core/src/models/Generator.ts
- packages/core/src/models/PackageAPI.ts
- packages/core/src/utils/createApp.ts
- packages/core/src/utils/createFiles.ts
- packages/core/src/utils/dependenciesInstall.ts
- packages/core/src/utils/fileController.ts
- pnpm-lock.yaml
```
[x ] Bugfix
[ ] Feature
```
- Closes #
- Related to #
修复了文件创建过程中存在的一些错误
```
[ ] Yes
[ x] No
```
> fix: 🧩 修复了文件创建过程中存在的一些错误

- .vscode/launch.json
- package.json
- packages/@plugin/plugin-eslint/generator/index.cjs
- packages/@plugin/plugin-eslint/index.cjs
- packages/@plugin/plugin-eslint/package.json
- packages/@plugin/plugin-typescript/generator/index.cjs
- packages/@plugin/plugin-typescript/generator/template/tsconfig.json
- packages/@plugin/plugin-typescript/package.json
- packages/core/src/models/Generator.ts
- packages/core/src/utils/createApp.ts
- packages/core/src/utils/createFiles.ts
- packages/core/src/utils/dependenciesInstall.ts
```
[x] Bugfix
[ ] Feature
```
- Closes #
- Related to #
在任何地方都可以获取到template，终端格式化完成。
```
[ ] Yes
[ ] No
```
> fix: 🧩 路径修改以及终端输出样式修改

- packages/core/src/models/FileTree.ts
- packages/core/src/models/Generator.ts
- packages/core/src/utils/dependenciesInstall.ts
```
[ ] Bugfix
[ x ] Feature
```
- Closes #
- Related to #
```
[ ] Yes
[ ] No
```
> feat: 🚀 add file tree

- packages/@plugin/plugin-babel/config/index.cjs
- packages/@plugin/plugin-babel/config/vite.cjs
- packages/@plugin/plugin-babel/config/webpack.cjs
- packages/@plugin/plugin-babel/index.cjs
- packages/core/src/models/FileTree.ts
- packages/core/src/models/Generator.ts
- packages/core/src/utils/ast.ts
- packages/core/src/utils/ast/commonAst.ts
- packages/core/src/utils/ast/parseAst.ts
- packages/core/src/utils/dependenciesInstall.ts
```
[ ] Bugfix
[ √ ] Feature
```
- Closes #152 
ast合并vite配置功能 
```
[ ] Yes
[ √] No
```
> feat: 🚀 ast合并vite配置功能

- packages/@plugin/plugin-eslint/generator/index.cjs
- packages/core/src/models/ConfigTransform.ts
- packages/core/src/models/FileTree.ts
- packages/core/src/models/Generator.ts
- packages/core/src/models/GeneratorAPI.ts
- packages/core/src/utils/createApp.ts
- packages/core/src/utils/preset.ts
- packages/core/src/utils/select.ts
```
[ ] Bugfix
[ ] Feature
```
- Closes #160 
根据FileTree重新修改生成插件配置文件方法。
```
[ ] Yes
[✅] No
```
> refactor: 修改生成插件配置文件方法

- package.json
- packages/core/package.json
- packages/core/src/types/index.ts
- packages/core/src/utils/constants.ts
- packages/core/src/utils/createApp.ts
- packages/core/src/utils/preset.ts
- packages/core/src/utils/select.ts
- packages/core/template/webpack.config.js
- pnpm-lock.yaml
```
[ ✅] Bugfix
[ ] Feature
```
- Closes #
- Related to #
修改 webpack 配置中模块引入类型错误以及为 package.json 添加相关的 dependent
```
[ ] Yes
[ ] No
```
> fix: 🧩 修改 webpack 配置中模块引入类型错误以及为 package.json 添加相关的 dependent

- packages/core/src/utils/constants.ts
- packages/core/src/utils/createApp.ts
- pnpm-lock.yaml
```
[√ ] Bugfix
[ ] Feature
```
- Closes #
- Related to #
修复构建工具缺少相关 dependentcies 依赖的问题
```
[ ] Yes
[ ] No
```
> fix: 🧩 修复构建工具缺少相关 dependentcies 依赖的问题

- packages/core/src/utils/preset.ts
- packages/core/src/utils/select.ts
```
[ ] Bugfix
[ ] Feature
```
- Closes #166 
新增默认预设供用户选择。
```
[ ] Yes
[✅] No
```
> feat: 增加默认预设选项

- packages/core/template/template-vue/generator/index.cjs
- packages/core/template/template-vue/generator/template/src/index.css
- packages/core/template/template-vue/generator/template/src/index.vue
- packages/core/template/template-vue/index.cjs
```
[ ] Bugfix
[x] Feature
```
- Closes https://github.com/xun082/create-neat/issues/54
- Related to https://github.com/xun082/create-neat/issues/24
新增 vue 模版
```
[ ] Yes
[x] No
```
> feat: 新增 vue 模版

- packages/@plugin/plugin-prettier/generator/index.cjs
- packages/@plugin/plugin-prettier/index.cjs
```
[ ] Bugfix
[√ ] Feature
```
- Closes #127
增加 prettier 插件入口 cjs文件
```
[ ] No
```
>  feat: 🚀 增加 prettier 插件入口 cjs文件

- packages/core/template/template-react/generator/index.cjs
- packages/core/template/template-react/generator/template/src/index.css
- packages/core/template/template-react/generator/template/src/index.jsx
- packages/core/template/template-react/index.cjs
```
[ ] Bugfix
[√ ] Feature
```
- Closes #55 
```
[ ] Yes
[ ] No
```
> feat: 新增 react 模板

- packages/@plugin/plugin-swc/config/webpack.config.js
- packages/@plugin/plugin-swc/generator/index.js
- packages/@plugin/plugin-swc/index.js
- packages/@plugin/plugin-swc/package.json
```
[ ] Bugfix
[ √] Feature
```
- Closes #169 
新增 swc 插件
```
[ ] Yes
[ x] No
```
> feat: 🚀 新增 swc 插件

- packages/core/src/utils/options.ts
- packages/core/src/utils/preset.ts
- packages/core/src/utils/select.ts
```
[ ] Bugfix
[ ] Feature
```
- Closes #167 
增加记录用户自定义预设到框架配置文件.neatrc中的功能
```
[ ] Yes
[✅] No
```
> feat: 增加记录用户自定义预设功能

- packages/@plugin/plugin-eslint/generator/index.cjs
- packages/@plugin/plugin-eslint/index.cjs
- packages/@plugin/plugin-prettier/generator/index.cjs
- packages/@plugin/plugin-prettier/index.cjs
/## PR Checklist
```
[√ ] Bugfix
[ ] Feature
```
- Closes #
- Related to #
修复 eslint 的依赖错误
```
[ ] Yes
[√ ] No
```
> fix: 🧩 修复 eslint 的依赖错误

- packages/@plugin/plugin-babel/package.json
- packages/@plugin/plugin-eslint/package.json
- packages/@plugin/plugin-prettier/generator/index.cjs
- packages/@plugin/plugin-prettier/index.cjs
- packages/@plugin/plugin-prettier/package.json
- packages/@plugin/plugin-swc/package.json
- packages/@plugin/plugin-typescript/package.json
- packages/core/template/template-react/generator/index.cjs
- packages/core/template/template-vue/generator/index.cjs
```
[ ] Bugfix
[ ] Feature
[√ ] Other... Please describe:
```
- Closes #
- Related to #
修改插件的包名
```
[ ] Yes
[ ] No
```
> style: 🎨 修改插件的包名

- packages/core/src/utils/createApp.ts
- packages/core/template/gitignore
```
[ ] Bugfix
[x] Feature
```
- Closes  [调研通用脚手架在项目创建后的收尾操作，可行则实现 #56 ](https://github.com/xun082/create-neat/issues/56)
- Related to #
新增.gitignore文件，计算下载包时间
```
[ ] Yes
[√] No
```
> feat: 🚀 新增.gitignore文件，计算下载包时间

- packages/core/src/utils/constants.ts
- packages/core/src/utils/fileController.ts
```
[ x ] Bugfix
[ ] Feature
```
- Closes #
- Related to #
修复mac无法删除目录问题
```
[ ] Yes
[ x ] No
```
> fix: 🧩 修复mac无法删除目录问题

- packages/core/src/models/FileTree.ts
```
[ ] Bugfix
[x] Feature
```
- Closes #
- Related to #
```
[ ] Yes
[x] No
```
> feat: 🚀 文件树设计文件后缀修改的内容抽离为中间件处理

- packages/@plugin/plugin-swc/generator/index.cjs
- packages/@plugin/plugin-swc/index.cjs
- packages/@plugin/plugin-swc/index.js
- packages/core/src/models/Generator.ts
- packages/core/src/types/index.ts
- packages/core/src/utils/select.ts
- pnpm-lock.yaml
```
[ ] Bugfix
[ ] Feature
[√ ] Other... Please describe:
```
- Closes #
- Related to #
修改脚手架命令行列表
```
[ ] Yes
[ ] No
```
> style: 🎨 修改脚手架命令行列表

- packages/@plugin/plugin-swc/config/index.cjs
- packages/@plugin/plugin-swc/config/vite.config.js
- packages/@plugin/plugin-swc/index.cjs
- packages/core/src/models/Generator.ts
- [✅] The commit message follows our guidelines: https://github.com/xun082/create-neat/blob/master/CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
```
- Closes #
- Related to #
新增swc插件出口文件，用于构建工具配置文件的合并
```
[ ] Yes
[✅] No
```
> feat: 增加swc插件出口文件

- packages/@plugin/plugin-babel/config/index.cjs
- packages/@plugin/plugin-babel/config/webpack.react.cjs
- packages/@plugin/plugin-babel/config/webpack.vue.cjs
- packages/@plugin/plugin-babel/generator/index.cjs
- packages/@plugin/plugin-babel/index.cjs
- packages/core/src/models/Generator.ts
- [✅] The commit message follows our guidelines: https://github.com/xun082/create-neat/blob/master/CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
```
- Closes #
- Related to #
注入框架变量让插件可以根据变量生成对应框架得配置文件，比如babel插件得配置文件
```
[ ] Yes
[✅] No
```
> feat: 优化插件配置注入框架变量

- packages/@plugin/plugin-babel/config/index.cjs
- packages/@plugin/plugin-babel/config/webpack.react.cjs
- packages/@plugin/plugin-babel/config/webpack.vue.cjs
- packages/@plugin/plugin-eslint/generator/index.cjs
- packages/@plugin/plugin-eslint/index.cjs
- packages/core/src/utils/createApp.ts
- packages/core/src/utils/createFiles.ts
- packages/core/src/utils/fileController.ts
- packages/core/src/utils/generateWebpackConfigFromEJS.ts
- packages/core/template/webpack.config.ejs
```
[ ] Bugfix
[ ] Feature
```
- Closes #
- Related to #
修复 webpack 配置错误,以及require.resolve引起的一些模块加载错误
```
[ ] Yes
[ ] No
```
> fix: 🧩 修复 webpack 配置错误,以及require.resolve引起的一些模块加载错误

- .github/workflows/build.yml
- .github/workflows/lint.yml
- package.json
- packages/@plugin/plugin-babel/package.json
- packages/@plugin/plugin-swc/package.json
- packages/@plugin/plugin-typescript/package.json
- pnpm-lock.yaml
- tsconfig.json
- turbo.json
- Closes #
- Related to #
fix: 🧩 升级turbo版本并修复打包错误
> fix: 🧩 升级turbo版本并修复打包错误

- packages/core/template/rollup.config.ejs
- Closes #
- Related to #
add rollup support
> feat: 🚀 add rollup support

- package.json
- packages/core/tsconfig.json
- pnpm-lock.yaml
- tsconfig.json
- turbo.json
- Closes #
- Related to #
修复 core 包打包失败
> fix: 🧩 修复 core 包打包失败

- .husky/pre-commit
- packages/core/src/utils/ast/parseAst.ts
- packages/core/src/utils/createApp.ts
> refactor: 使用ast合并构建工具配置文件

- packages/@plugin/plugin-mobx/generator/index.cjs
- packages/@plugin/plugin-mobx/generator/template/src/store/index.js
- packages/@plugin/plugin-mobx/index.cjs
- packages/@plugin/plugin-mobx/package.json
- packages/core/src/models/Generator.ts
- packages/core/src/utils/select.ts
- packages/core/template/template-react/generator/template/src/index.jsx
- Closes #216 
- Related to #217 
特定框架专属插件架构设计与实现
> feat: 特定框架专属插件架构设计与实现

- package.json
- packages/core/src/utils/createApp.ts
- packages/core/src/utils/fileController.ts
- Closes #
- Related to #
新增 webpack 相关启动文件
> feat: 🚀 新增 webpack 相关启动文件

- packages/core/src/models/Generator.ts
- packages/core/src/utils/createApp.ts
- packages/core/template/template-webpack-script/generator/index.cjs
- Closes #
- Related to #
将与webpack以及框架有关的scrpits和相关依赖合并到package.json中用来启动项目
> feat: 将与webpack构建工具有关的scripts以及依赖合并到package.json中用来启动项目

- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/utils/checkVersion.ts
- pnpm-lock.yaml
> feat: 用户输入简写、错误命令判断与指正、版本更新提示

- packages/utils/src/core/devServerConfig.ts
- Closes #
- Related to #
删除冗余代码。
> refactor:♻ 删除冗余代码。

- .prettierignore
- packages/core/src/models/FileTree.ts
- packages/core/src/models/Generator.ts
- packages/core/src/utils/createApp.ts
- packages/core/template/template-react/generator/template/public/index.html
- pnpm-lock.yaml
- [√] The commit message follows our guidelines: https://github.com/xun082/create-neat/blob/master/CONTRIBUTING.md
- [√] Bugfix
- Closes #
- Related to #
修复创建项目时htmlWebpackPlugin插件报错问题
- [] Yes
- [√] No
> fix: 修复创建项目时htmlWebpackPlugin插件报错问题

- .eslintignore
- packages/@plugin/plugin-pinia/config/index.cjs
- packages/@plugin/plugin-pinia/generator/index.cjs
- packages/@plugin/plugin-pinia/index.cjs
- packages/@plugin/plugin-pinia/package.json
- packages/core/src/models/Generator.ts
- packages/core/src/utils/select.ts
- packages/core/template/template-vue/generator/template/src/main.js
- pnpm-lock.yaml
-  The commit message follows our guidelines: https://github.com/xun082/create-neat/blob/master/CONTRIBUTING.md
-  Feature
- Closes #
- Related to #
-  No
> feat: add @plugin/plugin-pinia

- packages/core/src/models/FileTree.ts
- packages/core/src/models/Generator.ts
- pnpm-lock.yaml
> refactor: 修复core中一些方法变量的拼写错误

- packages/core/src/models/FileTree.ts
> fix: BUG 创建已存在文件导致报错

- packages/core/src/utils/select.ts
- pnpm-lock.yaml
> feat: 新增特殊插件选择

- packages/core/src/models/FileTree.ts
- packages/core/src/models/Generator.ts
处理解决 package.json 没正常创建，导致后续读取 package.json 报错。
主要集中于 Generator.ts 文件中 Generator 类中创建文件没 await
> fix: BUG 创建 package.json 及其他文件失败，导致读取 package.json 报错

- packages/core/src/models/BaseAPI.ts
- packages/core/src/models/FileTree.ts
- packages/core/src/models/protocolGenerator/PluginToTemplateAPI.ts
- packages/core/src/models/protocolGenerator/ProtocolGeneratorAPI.ts
- packages/core/template/template-react/generator/template/src/App.jsx
- packages/core/template/template-vue/generator/template/src/main.js
reactRouter插件对框架JSX部分影响抽离EJS实现
- [ x] The commit message follows our guidelines: https://github.com/xun082/create-neat/blob/master/CONTRIBUTING.md
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
- [ x] Refactoring (no functional changes, no api changes)
- Closes #
- Related to #
- [ x] No
> feat: 🚀 reactRouter插件对框架JSX部分影响抽离EJS实现

- packages/core/src/configs/protocol.ts
- packages/core/src/models/BaseAPI.ts
- packages/core/src/models/Generator.ts
- packages/core/src/models/protocolGenerator/TemplateToBuildToolAPI.ts
- pnpm-lock.yaml
> feat: 🚀 重新实现框架对构建工具协议

- packages/@plugin/plugin-pinia/generator/index.cjs
- packages/@plugin/plugin-pinia/index.cjs
- packages/@plugin/plugin-react-router/generator/index.cjs
- packages/@plugin/plugin-scss/generator/index.cjs
- packages/core/src/configs/protocol.ts
- packages/core/src/models/BaseAPI.ts
- packages/core/src/models/FileTree.ts
- packages/core/src/models/protocolGenerator/PluginToTemplateAPI.ts
- packages/core/src/models/protocolGenerator/ProtocolGeneratorAPI.ts
- packages/core/src/models/protocolGenerator/TemplateToBuildToolAPI.ts
- packages/core/src/types/protocol.ts
- packages/core/src/utils/commonUtils.ts
- packages/core/template/template-vue/generator/template/src/main.js
reactRouter及pinia插件对框架影响重构
- [ x] The commit message follows our guidelines: https://github.com/xun082/create-neat/blob/master/CONTRIBUTING.md
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
- [x ] Refactoring (no functional changes, no api changes)
- Closes #
- Related to #
- [ x] No
> refactor: ♻️ reactRouter及pinia插件对框架影响重构

- packages/@plugin/plugin-husky/generator/index.cjs
- packages/core/src/models/BaseAPI.ts
- packages/core/src/models/Generator.ts
- packages/core/src/utils/createApp.ts
- packages/core/src/utils/fileController.ts
- Closes #215 
- Related to #214 
实现 husky 插件的协议化配置
> feat: husky 协议配置

- packages/@plugin/plugin-pinia/generator/template/src/store/index.js
- packages/core/src/utils/createApp.ts
- Closes #
- Related to #
创建文件夹将在选择preset后创建。
重构`createApp.ts`逻辑
格式化pinia插件中的`index.js`确保通过ci。
> refactor: ♻️ 创建文件夹时机修改

- .github/workflows/lint.yml
- packages/@plugin/plugin-pinia/generator/template/src/store/index.js
- packages/core/src/configs/protocol.ts
- Closes #
- Related to #
protocol使用时会出现提醒注释并类型更明确
ci 添加了 Node Version 用来查看线上 Node 版本
> refactor: ♻️ protocol导出方式改成esm并加上jsdoc注释

- scripts/check_commit_msg.sh
> fix: 修改commit检查规则，允许merge类信息

- packages/@plugin/plugin-mobx/tsconfig.json
- packages/@plugin/tsconfig.json
> fix: 修复因ts编译器识别mobx模版文件为业务代码导致pnpm dev编译出错的问题
